blueprint:
  name: Lighting – No-Entry Guard (Dim then Off)
  description: >
    After the light turns ON, wait for presence or doorway motion.
    If nobody shows up within Dim window, dim. If still nobody by Off window, turn off.
    Doorway sensor is optional; you may set it to the same entity as presence if desired.
  domain: automation
  input:
    light_entity:
      name: Light (or group)
      selector:
        entity:
          domain: light
    presence_sensor:
      name: Presence / Motion inside room (binary_sensor)
      selector:
        entity:
          domain: binary_sensor
    doorway_sensor:
      name: (Optional) Doorway/Hall PIR (binary_sensor)
      default: ""
      selector:
        entity:
          domain: binary_sensor
          multiple: false
    dim_after_min:
      name: Dim if nobody enters within (minutes)
      default: 2
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
          mode: slider
    off_after_total_min:
      name: Turn off if nobody enters within (total minutes since ON)
      default: 6
      selector:
        number:
          min: 2
          max: 120
          unit_of_measurement: min
          mode: slider
    dim_scene:
      name: Scene to activate for "dim" (optional; uses brightness 20% if blank)
      default: ""
      selector:
        entity:
          domain: scene
          multiple: false
    dim_transition_sec:
      name: Dim transition (seconds)
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: s
          mode: slider

mode: restart

variables:
  i_dim_scene: !input dim_scene
  i_dim_min: !input dim_after_min
  i_off_total: !input off_after_total_min
  i_doorway: !input doorway_sensor

trigger:
  - platform: state
    entity_id: !input light_entity
    to: "on"

condition: []

action:
  # If already occupied when the light turns on, skip the no-entry waits entirely.
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input presence_sensor
                state: "on"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ i_doorway is defined and i_doorway != '' }}"
                  - condition: state
                    entity_id: !input doorway_sensor
                    state: "on"
        sequence:
          - stop: "Already occupied; skipping no-entry timeouts"

  # Window 1: up to dim_after_min to detect presence (and doorway if provided)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ i_doorway != '' }}"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input presence_sensor
                to: "on"
              - platform: state
                entity_id: !input doorway_sensor
                to: "on"
            timeout:
              minutes: !input dim_after_min
            continue_on_timeout: true
      - conditions:
          - condition: template
            value_template: "{{ i_doorway == '' }}"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input presence_sensor
                to: "on"
            timeout:
              minutes: !input dim_after_min
            continue_on_timeout: true

  # If timed out (nobody entered) and light still on -> dim
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ not wait.completed }}"
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ i_dim_scene != '' }}"
                sequence:
                  - service: hue.activate_scene
                    target:
                      entity_id: !input dim_scene
                    data:
                      transition: !input dim_transition_sec
            default:
              - service: light.turn_on
                target:
                  entity_id: !input light_entity
                data:
                  brightness_pct: 20
                  transition: !input dim_transition_sec

  # Window 2: until total off_after_total_min — if still nobody, turn OFF
  - variables:
      remaining_min: >
        {{ [ ( i_off_total | int ) - ( i_dim_min | int ), 0 ] | max }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ i_doorway != '' }}"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input presence_sensor
                to: "on"
              - platform: state
                entity_id: !input doorway_sensor
                to: "on"
            timeout:
              minutes: "{{ remaining_min }}"
            continue_on_timeout: true
      - conditions:
          - condition: template
            value_template: "{{ i_doorway == '' }}"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input presence_sensor
                to: "on"
            timeout:
              minutes: "{{ remaining_min }}"
            continue_on_timeout: true

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ not wait.completed }}"
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
